### ISSUE TITLE
CPU Temp missing

### ISSUE THREAD

**Issue by indefa** [SmokeyMcBong/StreamDeckMonitor#2]
Hey man, 
Love the work you've done here. However I find myself unable to use Stream Deck Monitor because OpenHardwareMonitor can't show temps for my 2700x :(

Every other reading works perfect and I can see my CPU temps in other programs but OpenHardwareMonitor just doesn't seem to work.

**Comment by SmokeyMcBong** [comment]
Hi mate, Thank you :)  

It looks like the Librehardwaremonitor library maybe hasn't had the 2600x and 2700x support added just yet, BUT It seems that AquaComputer's have forked the Openhardwaremonitor repo and have added support for the 2600+2700x cpu's
I will fork and compile their patched version of the library and upload here for you to test if you like mate?

just a case of navigating to 'StreamDeckMonitor_v6.0\ext\libs\LibreHardwareMonitor' and replacing the OpenHardwareMonitorLib.dll with the one i will provide shortly

hopefully this helps for now mate 


Take care


SmokeyMcBong

**Comment by SmokeyMcBong** [comment]
Have just compiled AquaComputer's OpenHardwareMonitor Fork.
Here is the library file, It should have support for your cpu, but there may be missing patches or features/fixes that were added to LibreHardwareMonitor and not yet patched into AquaComputer's OpenHardwareMonitor Fork repo.

[OpenHardwareMonitorLib.zip](https://github.com/SmokeyMcBong/StreamDeckMonitor/files/2270237/OpenHardwareMonitorLib.zip)


Hope this helps mate,

Take care


SmokeyMcBong

**Comment by SmokeyMcBong** [comment]
LibreHardwareMonitor have merged the changes made by AquaComputers to add support for the AMD 2600x and 2700x CPU's.

I have compiled and added the library

 https://github.com/SmokeyMcBong/StreamDeckMonitor/releases/tag/v6.1


v6.1 and all newer versions should be ok reading these temperatures

**Comment by indefa** [comment]
Unsure if I have done something wrong but I still don't seem to be getting a CPU temp reading. 

Completely deleted all other versions off my PC and set up v6.1. The CPU temp button is blank. I did also try replacing the Lib with the one you linked earlier just in case there was something wrong with the one complied here but same issue.

**Comment by SmokeyMcBong** [comment]
@indefa , Hi mate, I've compiled the complete LibreHardwareMonitor project from the latest source 

[LibreHardwareMonitor-01-09-18.zip](https://github.com/SmokeyMcBong/StreamDeckMonitor/files/2342197/LibreHardwareMonitor-01-09-18.zip)

Could you please extract the contents and run the OpenHardwareMonitor.exe.
Does the CPU section show any CPU temps? 

I'm hoping that maybe the CPU temperature is not being read properly by StreamDeckMonitor because of a name mismatch
testing the original LibreHardwareMonitor app will show if it's reading the CPU temperature properly and whether there is a name mismatch. 

It should show something similar to 'CPU Package' in the CPU temperature section 
does it show this heading and also does it show the current CPU temp?

Would it be possible for you to take a screenshot of LibreHardwareMonitor while its running to show what sensors are being read and how they are named please?

**Comment by indefa** [comment]
@SmokeyMcBong Looks as though the temps are working in Open Hardware Monitor. Here is a screenshot for you.
https://i.imgur.com/3KwVjWU.png

**Comment by SmokeyMcBong** [comment]
@indefa That is perfect thank you!  
Thats good news, It is just a naming mismatch, I will add the temperature reference for the Ryzen series

Thank you for your help mate 👍

**Comment by SmokeyMcBong** [comment]
@indefa  Hi mate, here's a test build with what should hopefully be the correct temperature reference 

~~https://github.com/SmokeyMcBong/StreamDeckMonitor/releases/download/v6.2-Testing~~

10/09 - v7.6 is available from the releases section
